### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by GodStar88** [brunobrandes/fullcontact-api-csharp#5]
Hello.
I am C# developer
var person = fullContactAppService.GetAsync(Lookup.Email, "bart@fullcontact.com").Result;
It work in console but doesn't work windowsForm.  ( this line stop)
How?
Please help me.
Regards

**Comment by oflahero** [comment]
Sounds like another case for probably the most linked-to blog post on async code in history: https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

I doubt this is an issue for this repo, rather a Task.Run() issue!

**Comment by oflahero** [comment]
Possible idea for this repo project: use recommended practice of setting .ConfigureAwait(false) on async calls in methods where possible. This ensures continuations are scheduled on threadpool threads and not on (potentially blocking) UI threads/ASP.NET request threads.

**Comment by GodStar88** [comment]
Hello.

I got the issue,  can you help me?

Newtonsoft.Json.JsonSerializationException: Error converting value "avatar" to type 'FullContact.Domain.Enum.SocialProfileType'. Path 'photos[0].typeId', line 7, position 23. ---> System.ArgumentException: Requested value 'avatar' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Boolean disallowValue, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at FullContact.Infrastructure.Serializers.JsonSerializer`1.Deserialize(String message) in D:\git-projects\fullcontact-api-csharp\src\Infrastructure\FullContact.Infrastructure\Serializers\JsonSerializer.cs:line 54
   at FullContact.Application.Service.FullContactAppService`1.<GetAsync>d__10.MoveNext() in D:\git-projects\fullcontact-api-csharp\src\ApplicationService\FullContact.Application.Service\FullContactAppService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Search_Clients.CFullContact.<FullcontactTwitterAsync>d__2.MoveNext() in E:\Work\VC\Bot\11 - Client Builder\Client Builder\Classes\CFullContact.cs:line 117

**Comment by brunobrandes** [comment]
@GodStar88  
I commited change "add 'avatar' social profile enum value"
Update your nuget.

Hugs
